import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { HistoryListComponent } from './components/history-list/history-list.component';
import { RequestsListComponent } from './components/requests-list/requests-list.component';
import { ContainerComponent } from '../../common/components/container/container.component';
import { OutageListComponent} from './components/outage-list/outage-list.component';
import { PublicComponent } from '../../common/components/public-page/public/public.component';
import { DelegationComponent } from './components/delegation/delegation.component';
import { ActionCardsComponent } from './components/action-cards/action-cards.component';
import { ServicenowTicketsListComponent } from './components/servicenow-tickets-list/servicenow-tickets-list.component';
import { SearchPageComponent } from '../../common/components/search-page/search-page.component';
//import { WelcomeComponent } from '../../common/components/welcome/welcome.component';

const routes: Routes = [
    // { path: '', redirectTo: 'home', pathMatch: 'full' },
    // { path: 'en', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
    // { path: 'cs/Sites', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
    // { path: 'customercare', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
    { path: 'cs/Sites', redirectTo: 'home', pathMatch: 'full' },
    { path: 'en/customercare', redirectTo: 'en/home/', pathMatch: 'full' },
    { path: 'home', redirectTo: 'en/home/', pathMatch: 'full' },
    { path: 'en/requests', redirectTo: 'en/home/#myrequests', pathMatch: 'full' },
    { path: 'en/history', redirectTo: 'en/home/#history' },
    { path: 'en/delegation', redirectTo: 'en/home/#dgrequests', pathMatch: 'full' },
    { path: 'en/serviceoutage', redirectTo: 'en/home/#serviceoutage' },
    // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
     { path: 'en/home/', component: RequestsListComponent },
    { path: 'en/home', component: RequestsListComponent },
    { path: 'en/search', component: SearchPageComponent },
    
    { path: 'en/home/#myrequests', component: RequestsListComponent },
    { path: 'en/home/#myrequests#modal', component: RequestsListComponent },
    { path: 'en/home/#dgrequests', component: DelegationComponent },
    { path: 'en/home/#dgrequests#modal', component: DelegationComponent },
    { path: 'en/home/#history', component: HistoryListComponent },
    { path: 'en/home/#serviceoutage', component: OutageListComponent },
    { path: 'en/home/#serviceoutage#modal', component: OutageListComponent },
    { path: 'en/home/#history#modal', component: HistoryListComponent },
    { path: 'en/index', component: HistoryListComponent },
    { path: 'en/public', component: PublicComponent },
    { path: 'en/public/', component: PublicComponent},
    { path: 'en/public/#snmyrequests', component: ServicenowTicketsListComponent },
    { path: 'en/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
    { path: 'en/public/#snhistoryrequests', component: ServicenowTicketsListComponent },
    { path: 'en/public/#snhistoryrequests?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
    //{ path: 'en/public/#myrequests#modal', component: RequestsListComponent },
    //{ path: 'en/public/#history?view=AvayaCloudOffice', component: HistoryListComponent },
    //{ path: 'en/public/#history#modal', component: HistoryListComponent },
    //{ path: 'en/public/AvayaCloudOffice',redirectTo: 'en/public', pathMatch: 'full'},
    //{path :'en/welcome',component:WelcomeComponent,pathMatch:'full'},
  

  // { path: '', redirectTo: 'home', pathMatch: 'full' },
  // { path: 'cs/Sites', redirectTo: 'home', pathMatch: 'full' },
  // { path: 'home', redirectTo: 'en/home', pathMatch: 'full' },
  // { path: 'en/home', component: RequestsListComponent },
  // { path: 'requests', redirectTo: 'en/requests', pathMatch: 'full' },
  // { path: 'en/requests', component: RequestsListComponent },
  // { path: 'history', redirectTo: 'en/history' },
  // { path: 'en/history', component: HistoryListComponent, pathMatch: 'full' },
  // { path: '**', redirectTo: 'en/home', pathMatch: 'full' }
  //{ path: 'cs/Sites', redirectTo: 'home', pathMatch: 'full' },
  { path: 'fr/customercare', redirectTo: 'fr/home/', pathMatch: 'full' },
  //{ path: 'fr/home', redirectTo: 'fr/home/', pathMatch: 'full' },
  { path: 'fr/requests', redirectTo: 'fr/home/#myrequests', pathMatch: 'full' },
  { path: 'fr/history', redirectTo: 'fr/home/#history' },
  { path: 'fr/delegation', redirectTo: 'fr/home/#dgrequests', pathMatch: 'full' },
  { path: 'fr/serviceoutage', redirectTo: 'fr/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'fr/home/', component: RequestsListComponent },
  { path: 'fr/home', component: RequestsListComponent },
  { path: 'fr/home/#myrequests', component: RequestsListComponent },
  { path: 'fr/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'fr/home/#dgrequests', component: DelegationComponent },
  { path: 'fr/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'fr/home/#history', component: HistoryListComponent },
  { path: 'fr/home/#serviceoutage', component: OutageListComponent },
  { path: 'fr/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'fr/home/#history#modal', component: HistoryListComponent },
  { path: 'fr/index', component: HistoryListComponent },
  { path: 'fr/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'fr/public/', component: PublicComponent},
  { path: 'fr/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'fr/search', component: SearchPageComponent },
  //{ path: 'en/public/AvayaCloudOffice',redirectTo: 'en/public', pathMatch: 'full'},
  //{path :'en/welcome',component:WelcomeComponent,pathMatch:'full'},

  { path: 'it/customercare', redirectTo: 'it/home/', pathMatch: 'full' },
  //{ path: 'it/home', redirectTo: 'it/home/', pathMatch: 'full' },
  { path: 'it/requests', redirectTo: 'it/home/#myrequests', pathMatch: 'full' },
  { path: 'it/history', redirectTo: 'it/home/#history' },
  { path: 'it/delegation', redirectTo: 'it/home/#dgrequests', pathMatch: 'full' },
  { path: 'it/serviceoutage', redirectTo: 'it/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'it/home/', component: RequestsListComponent },
  { path: 'it/home', component: RequestsListComponent },
  { path: 'it/home/#myrequests', component: RequestsListComponent },
  { path: 'it/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'it/home/#dgrequests', component: DelegationComponent },
  { path: 'it/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'it/home/#history', component: HistoryListComponent },
  { path: 'it/home/#serviceoutage', component: OutageListComponent },
  { path: 'it/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'it/home/#history#modal', component: HistoryListComponent },
  { path: 'it/index', component: HistoryListComponent },
  { path: 'it/public', component: PublicComponent , pathMatch: 'full' },
  { path: 'it/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'it/search', component: SearchPageComponent },



  { path: 'de/customercare', redirectTo: 'de/home/', pathMatch: 'full' },
 // { path: 'de/home', redirectTo: 'de/home/', pathMatch: 'full' },
  { path: 'de/requests', redirectTo: 'de/home/#myrequests', pathMatch: 'full' },
  { path: 'de/history', redirectTo: 'de/home/#history' },
  { path: 'de/delegation', redirectTo: 'de/home/#dgrequests', pathMatch: 'full' },
  { path: 'de/serviceoutage', redirectTo: 'de/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'de/home/', component: RequestsListComponent },
  { path: 'de/home', component: RequestsListComponent },
  { path: 'de/home/#myrequests', component: RequestsListComponent },
  { path: 'de/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'de/home/#dgrequests', component: DelegationComponent },
  { path: 'de/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'de/home/#history', component: HistoryListComponent },
  { path: 'de/home/#serviceoutage', component: OutageListComponent },
  { path: 'de/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'de/home/#history#modal', component: HistoryListComponent },
  { path: 'de/index', component: HistoryListComponent },
  { path: 'de/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'de/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'de/search', component: SearchPageComponent },
  

  { path: 'es/customercare', redirectTo: 'es/home/', pathMatch: 'full' },
 // { path: 'es/home', redirectTo: 'es/home/', pathMatch: 'full' },
  { path: 'es/requests', redirectTo: 'es/home/#myrequests', pathMatch: 'full' },
  { path: 'es/history', redirectTo: 'es/home/#history' },
  { path: 'es/delegation', redirectTo: 'es/home/#dgrequests', pathMatch: 'full' },
  { path: 'es/serviceoutage', redirectTo: 'es/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'es/home/', component: RequestsListComponent },
  { path: 'es/home', component: RequestsListComponent },
  { path: 'es/home/#myrequests', component: RequestsListComponent },
  { path: 'es/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'es/home/#dgrequests', component: DelegationComponent },
  { path: 'es/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'es/home/#history', component: HistoryListComponent },
  { path: 'es/home/#serviceoutage', component: OutageListComponent },
  { path: 'es/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'es/home/#history#modal', component: HistoryListComponent },
  { path: 'es/index', component: HistoryListComponent },
  { path: 'es/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'es/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'es/search', component: SearchPageComponent },

  { path: 'ko/customercare', redirectTo: 'ko/home/', pathMatch: 'full' },
  //{ path: 'ko/home', redirectTo: 'ko/home/', pathMatch: 'full' },
  { path: 'ko/requests', redirectTo: 'ko/home/#myrequests', pathMatch: 'full' },
  { path: 'ko/history', redirectTo: 'ko/home/#history' },
  { path: 'ko/delegation', redirectTo: 'ko/home/#dgrequests', pathMatch: 'full' },
  { path: 'ko/serviceoutage', redirectTo: 'ko/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'ko/home/', component: RequestsListComponent },
  { path: 'ko/home', component: RequestsListComponent },
  { path: 'ko/home/#myrequests', component: RequestsListComponent },
  { path: 'ko/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'ko/home/#dgrequests', component: DelegationComponent },
  { path: 'ko/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'ko/home/#history', component: HistoryListComponent },
  { path: 'ko/home/#serviceoutage', component: OutageListComponent },
  { path: 'ko/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'ko/home/#history#modal', component: HistoryListComponent },
  { path: 'ko/index', component: HistoryListComponent },
  { path: 'ko/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'ko/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'ko/search', component: SearchPageComponent },

  
  { path: 'ru/customercare', redirectTo: 'ru/home/', pathMatch: 'full' },
  //{ path: 'ru/home', redirectTo: 'ru/home/', pathMatch: 'full' },
  { path: 'ru/requests', redirectTo: 'ru/home/#myrequests', pathMatch: 'full' },
  { path: 'ru/history', redirectTo: 'ru/home/#history' },
  { path: 'ru/delegation', redirectTo: 'ru/home/#dgrequests', pathMatch: 'full' },
  { path: 'ru/serviceoutage', redirectTo: 'ru/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'ru/home/', component: RequestsListComponent },
  { path: 'ru/home', component: RequestsListComponent },
  { path: 'ru/home/#myrequests', component: RequestsListComponent },
  { path: 'ru/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'ru/home/#dgrequests', component: DelegationComponent },
  { path: 'ru/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'ru/home/#history', component: HistoryListComponent },
  { path: 'ru/home/#serviceoutage', component: OutageListComponent },
  { path: 'ru/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'ru/home/#history#modal', component: HistoryListComponent },
  { path: 'ru/index', component: HistoryListComponent },
  { path: 'ru/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'ru/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'ru/search', component: SearchPageComponent },


  { path: 'zh/customercare', redirectTo: 'zh/home/', pathMatch: 'full' },
 // { path: 'zh/home', redirectTo: 'zh/home/', pathMatch: 'full' },
  { path: 'zh/requests', redirectTo: 'zh/home/#myrequests', pathMatch: 'full' },
  { path: 'zh/history', redirectTo: 'zh/home/#history' },
  { path: 'zh/delegation', redirectTo: 'zh/home/#dgrequests', pathMatch: 'full' },
  { path: 'zh/serviceoutage', redirectTo: 'zh/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'zh/home/', component: RequestsListComponent },
  { path: 'zh/home', component: RequestsListComponent },
  { path: 'zh/home/#myrequests', component: RequestsListComponent },
  { path: 'zh/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'zh/home/#dgrequests', component: DelegationComponent },
  { path: 'zh/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'zh/home/#history', component: HistoryListComponent },
  { path: 'zh/home/#serviceoutage', component: OutageListComponent },
  { path: 'zh/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'zh/home/#history#modal', component: HistoryListComponent },
  { path: 'zh/index', component: HistoryListComponent },
  { path: 'zh/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'zh/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'zh/search', component: SearchPageComponent },



  { path: 'ja/customercare', redirectTo: 'ja/home/', pathMatch: 'full' },
  //{ path: 'ja/home', redirectTo: 'ja/home/', pathMatch: 'full' },
  { path: 'ja/requests', redirectTo: 'ja/home/#myrequests', pathMatch: 'full' },
  { path: 'ja/history', redirectTo: 'ja/home/#history' },
  { path: 'ja/delegation', redirectTo: 'ja/home/#dgrequests', pathMatch: 'full' },
  { path: 'ja/serviceoutage', redirectTo: 'ja/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'ja/home/', component: RequestsListComponent },
  { path: 'ja/home', component: RequestsListComponent },
  { path: 'ja/home/#myrequests', component: RequestsListComponent },
  { path: 'ja/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'ja/home/#dgrequests', component: DelegationComponent },
  { path: 'ja/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'ja/home/#history', component: HistoryListComponent },
  { path: 'ja/home/#serviceoutage', component: OutageListComponent },
  { path: 'ja/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'ja/home/#history#modal', component: HistoryListComponent },
  { path: 'ja/index', component: HistoryListComponent },
  { path: 'ja/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'ja/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'ja/search', component: SearchPageComponent },

  { path: 'pt/customercare', redirectTo: 'pt/home/', pathMatch: 'full' },
 // { path: 'pt/home', redirectTo: 'pt/home/', pathMatch: 'full' },
  { path: 'pt/requests', redirectTo: 'pt/home/#myrequests', pathMatch: 'full' },
  { path: 'pt/history', redirectTo: 'pt/home/#history' },
  { path: 'pt/delegation', redirectTo: 'pt/home/#dgrequests', pathMatch: 'full' },
  { path: 'pt/serviceoutage', redirectTo: 'pt/home/#serviceoutage' },
  // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
  { path: 'pt/home/', component: RequestsListComponent },
  { path: 'pt/home', component: RequestsListComponent },
  { path: 'pt/home/#myrequests', component: RequestsListComponent },
  { path: 'pt/home/#myrequests#modal', component: RequestsListComponent },
  { path: 'pt/home/#dgrequests', component: DelegationComponent },
  { path: 'pt/home/#dgrequests#modal', component: DelegationComponent },
  { path: 'pt/home/#history', component: HistoryListComponent },
  { path: 'pt/home/#serviceoutage', component: OutageListComponent },
  { path: 'pt/home/#serviceoutage#modal', component: OutageListComponent },
  { path: 'pt/home/#history#modal', component: HistoryListComponent },
  { path: 'pt/index', component: HistoryListComponent },
  { path: 'pt/public', component: PublicComponent, pathMatch: 'full' },
  { path: 'pt/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
  { path: 'pt/search', component: SearchPageComponent },

  { path: 'nl/customercare', redirectTo: 'nl/home/', pathMatch: 'full' },
  // { path: 'pt/home', redirectTo: 'pt/home/', pathMatch: 'full' },
   { path: 'nl/requests', redirectTo: 'nl/home/#myrequests', pathMatch: 'full' },
   { path: 'nl/history', redirectTo: 'nl/home/#history' },
   { path: 'nl/delegation', redirectTo: 'nl/home/#dgrequests', pathMatch: 'full' },
   { path: 'nl/serviceoutage', redirectTo: 'nl/home/#serviceoutage' },
   // { path: 'en/home', redirectTo: '/en/home/#myrequests', pathMatch: 'full' },
   { path: 'nl/home/', component: RequestsListComponent },
   { path: 'nl/home', component: RequestsListComponent },
   { path: 'nl/home/#myrequests', component: RequestsListComponent },
   { path: 'nl/home/#myrequests#modal', component: RequestsListComponent },
   { path: 'nl/home/#dgrequests', component: DelegationComponent },
   { path: 'nl/home/#dgrequests#modal', component: DelegationComponent },
   { path: 'nl/home/#history', component: HistoryListComponent },
   { path: 'nl/home/#serviceoutage', component: OutageListComponent },
   { path: 'nl/home/#serviceoutage#modal', component: OutageListComponent },
   { path: 'nl/home/#history#modal', component: HistoryListComponent },
   { path: 'nl/index', component: HistoryListComponent },
   { path: 'nl/public', component: PublicComponent, pathMatch: 'full' },
   { path: 'nl/public?view=AvayaCloudOffice', component: ServicenowTicketsListComponent },
   { path: 'nl/search', component: SearchPageComponent },

  { path: 'en/404', component: PublicComponent },
  { path: 'fr/404', component: PublicComponent },
  { path: 'de/404', component: PublicComponent },
  { path: 'it/404', component: PublicComponent },
  { path: 'ko/404', component: PublicComponent },
  { path: 'ru/404', component: PublicComponent },
  { path: 'es/404', component: PublicComponent },
  { path: 'zh/404', component: PublicComponent },
  { path: 'ja/404', component: PublicComponent },
  { path: 'pt/404', component: PublicComponent }, 
  { path: 'nl/404', component: PublicComponent }, 

  

  { path: 'en/**', redirectTo: 'en/home/', pathMatch: 'full' },
  { path: 'it/**', redirectTo: 'it/home/', pathMatch: 'full' },
  { path: 'es/**', redirectTo: 'es/home/', pathMatch: 'full' },
  { path: 'de/**', redirectTo: 'de/home/', pathMatch: 'full' },
  { path: 'ko/**', redirectTo: 'ko/home/', pathMatch: 'full' },
  { path: 'ru/**', redirectTo: 'ru/home/', pathMatch: 'full' },
  { path: 'zh/**', redirectTo: 'zh/home/', pathMatch: 'full' },
  { path: 'ja/**', redirectTo: 'ja/home/', pathMatch: 'full' },
  { path: 'pt/**', redirectTo: 'pt/home/', pathMatch: 'full' },
  { path: 'nl/**', redirectTo: 'pt/home/', pathMatch: 'full' },
  
  //{ path: '**', redirectTo: 'en/home', pathMatch: 'full' }
  //{ path: '**', component: PublicComponent , pathMatch: 'full' },
  
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class CustomerCareRoutingModule { }
